---
# configuration-specific tasks file for openbao

- name: Create the OpenBao state directory
  ansible.builtin.file:
    dest: "{{ openbao_var_path }}"
    state: directory
    owner: "{{ openbao_service_user }}"
    group: "{{ caddy_group }}"
    mode: u=rwx,g=rx,o=
  tags:
    - openbao
    - caddy
    - configuration

- name: Create the OpenBao data directory
  ansible.builtin.file:
    dest: "{{ openbao_var_path }}/vault"
    state: directory
    owner: "{{ openbao_service_user }}"
    group: "{{ openbao_service_group }}"
    mode: u=rwx,g=rx,o=
  tags:
    - openbao
    - configuration

- name: Create the OpenBao certificate directory
  ansible.builtin.file:
    dest: "{{ openbao_var_path }}/certs"
    state: directory
    owner: "{{ openbao_service_user }}"
    group: "{{ caddy_group }}"
    mode: u=rwx,g=rx,o=
  tags:
    - openbao
    - caddy
    - configuration

- name: Create directory for Lego certificates
  ansible.builtin.file:
    path: "{{ lego_lib_path }}/{{ openbao_service_name }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=,o=
  tags:
    - openbao
    - lego
    - configuration

- name: Create or update the Lego configuration file
  ansible.builtin.template:
    src: lego.conf.jinja
    dest: "{{ lego_etc_path }}/{{ openbao_service_name }}.conf"
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify:
    - Trigger Lego for OpenBao certificate renewal
  tags:
    - openbao
    - lego
    - configuration

- name: Create or update the Lego post-run hook
  ansible.builtin.template:
    src: lego.sh.jinja
    dest: "{{ lego_usr_path }}/{{ openbao_service_name }}"
    owner: root
    group: root
    mode: u=rwx,g=,o=
  notify:
    - Trigger Lego for OpenBao certificate renewal
  tags:
    - openbao
    - lego
    - configuration

- name: Check for the OpenBao certificate files
  ansible.builtin.stat:
    path: "{{ certificate_file }}"
  loop:
    - "{{ openbao_var_path }}/certs/server.crt"
    - "{{ openbao_var_path }}/certs/server.key"
  loop_control:
    label: "{{ certificate_file }}"
    loop_var: certificate_file
  register: openbao_certificate_files
  tags:
    - openbao
    - lego
    - configuration

- name: Request the initial OpenBao certificate
  ansible.builtin.debug:
    msg: The OpenBao certificate or key does not exist and will be requested
  changed_when: >-
    openbao_certificate_files.results
    | selectattr('stat.exists', 'equalto', false)
    | list
    | length > 0
  notify:
    - Trigger Lego for OpenBao certificate renewal
  tags:
    - openbao
    - lego
    - configuration

- name: Issue the OpenBao certificate before configuring services
  ansible.builtin.meta: flush_handlers
  tags:
    - openbao
    - lego
    - configuration

- name: Set the OpenBao certificate file permissions
  ansible.builtin.file:
    path: "{{ certificate_file }}"
    state: file
    owner: "{{ openbao_service_user }}"
    group: "{{ caddy_group }}"
    mode: u=rw,g=r,o=
  loop:
    - "{{ openbao_var_path }}/certs/server.crt"
    - "{{ openbao_var_path }}/certs/server.key"
  loop_control:
    label: "{{ certificate_file }}"
    loop_var: certificate_file
  tags:
    - openbao
    - caddy
    - configuration

- name: Create or update the openbao.hcl configuration file
  ansible.builtin.template:
    src: openbao.hcl.jinja
    dest: "{{ openbao_etc_path }}/{{ openbao_etc_name }}"
    owner: "{{ openbao_service_user }}"
    group: "{{ openbao_service_group }}"
    mode: u=rw,g=r,o=
  notify:
    - Reload OpenBao
  tags:
    - openbao
    - configuration

- name: Create or update the openbao.fish configuration file
  ansible.builtin.template:
    src: openbao.fish.jinja
    dest: /root/.config/fish/conf.d/openbao.fish
    owner: root
    group: root
    mode: u=rw,g=r,o=
  tags:
    - openbao
    - configuration

- name: Create the OpenBao snapshots directory
  ansible.builtin.file:
    path: "{{ openbao_var_path }}/snapshots"
    state: directory
    owner: "{{ openbao_service_user }}"
    group: "{{ openbao_service_group }}"
    mode: u=rwx,g=rx,o=
  tags:
    - openbao
    - backup
    - configuration

- name: Create the OpenBao AWS credentials directory
  ansible.builtin.file:
    path: "{{ openbao_var_path }}/.aws"
    state: directory
    owner: "{{ openbao_service_user }}"
    group: "{{ openbao_service_group }}"
    mode: u=rwx,g=,o=
  tags:
    - openbao
    - backup
    - configuration

- name: Create or update the AWS credentials file
  ansible.builtin.template:
    src: credentials.jinja
    dest: "{{ openbao_var_path }}/.aws/credentials"
    owner: "{{ openbao_service_user }}"
    group: "{{ openbao_service_group }}"
    mode: u=rw,g=,o=
  tags:
    - openbao
    - backup
    - configuration

- name: Deploy the OpenBao raft backup script
  ansible.builtin.copy:
    src: openbao-raft-backup
    dest: /usr/local/bin/openbao-raft-backup
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - openbao
    - backup
    - configuration
