---
profile: production
sarif_file: results.sarif

# exclude_paths included in this file are parsed relative to this file's
# location and not relative to the CWD of execution. CLI arguments passed to the
# --exclude option are parsed relative to the CWD of execution.
exclude_paths:
  - .cache
  - .github
  - .github/workflows
  - .task
  - .taskfiles

use_default_rules: true
loop_var_prefix: ^(__|{role}_)
var_naming_pattern: ^[a-z][a-z0-9]*(_[a-z0-9]+)*[a-z0-9]$

skip_list:
  - var-naming[no-role-prefix]

# Ansible-lint does not automatically load rules that have the 'opt-in' tag.
# You must enable opt-in rules by listing each rule 'id' below.
enable_list:
  - args
  - empty-string-compare
  - no-log-password
  - no-same-owner
  - name
  - yaml

# ansible-lint does not fail on warnings from the rules or tags listed below
warn_list:
  - experimental

# List of additional kind:pattern to be added at the top of the default
# match list, first match determines the file kind.
kinds:
  - playbook: plays/*.yaml
  - vars: plays/*_vars/*.yaml
  - vars: roles/*/vars/*.yaml
  - tasks: roles/*/tasks/*.yaml
  - meta: roles/*/meta/main.yaml
# Allow setting custom prefix for name[prefix] rule
# task_name_prefix: '{stem} | '
