---
version: 3
output: prefixed

# This Taskfile is configured to minimise dependencies and run most tasks in a
# semi-sequential way, which reduces issues with parallel task contexts being
# cancelled following failures. This helps the interval stay low. However, if
# there are issues with tasks running continuously, or being re-added to the
# queue multiple times due to regular changes, increase the value for the watch
# interval to take into account the typical longest running task in the set.
interval: 2s

# Enforce the pipefail option in the Bash library to ensure that where commands
# are run through pipes, the failure of any one step in the pipeline fails the
# whole pipe. For example, terraform |& tee will not normally fail if Terraform
# fails as tee almost always will exit cleanly, unless pipefail is set.
set:
  - pipefail

env:
  limit: '{{ .limit | default "all" }}'

vars:
  # ANSI Colours
  cg: \e[0;31m
  cw: \e[1;37m
  cc: \e[0m

  # Work out the full path to the root of this repository to allow us to create
  # absolute paths to configuration files, caches, etc., rather than attempt to
  # generate relative links programmatically
  root:
    sh: git rev-parse --show-toplevel

tasks:
  default:
    desc: Run the development and integration tasks once
    summary: |-
      Clean the environment and then run the development and integration tasks
      for all resources by testing and checking the code and files, but only
      once rather than continuously.

      Use the following command for additional information on the steps
      involved:

      $ task --summary develop
    silent: true
    cmds:
      - task: develop

  develop:
    desc: Continuously run the development and integration tasks
    summary: |-
      The develop task is designed to perform continuous integration on code
      changes within this repository, first by cleaning the repository and then
      running the following tasks when any relevant files are changed.
    silent: true
    watch: true
    deps:
      - task: clean

  rename:
    desc: Find and rename all .yml files to .yaml
    sources:
      - "**.yml"
    silent: true
    cmds:
      - cmd: |-
          find -type f -iname '*.yml' | while read file
          do
            echo "${file#\./} -> $(basename $file .yml).yaml"
            git mv -f $file ${file%.yml}.yaml 2>/dev/null \
             || mv -f $file ${file%.yml}.yaml
          done

  clean:
    desc: Clean temporary files from the repository and configurations
    silent: true
    summary: |-
      Clean any temporary directories and files created by both this Taskfile,
      and the tools and applications called from it, and from within the
      configurations.
    run: once
    cmds:
      - cmd: rm -f .prettiercache
      - cmd: rm -rf .task
      - cmd: echo -e '{{ .cg }}Completed{{ .cc }}'
