---
galaxy_info:
  author: Jonathan Wright
  description: Create and install Secure Boot keys
  company: n3tuk
  issue_tracker_url: https://github.com/n3tuk/ansible/issues
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: ArchLinux
      versions:
        - all

  galaxy_tags:
    - kernels

dependencies: []
