---
# storage tasks for netdata

- name: Create the logical volume for Netdata
  community.general.lvol:
    vg: "{{ netdata_volume_group }}"
    lv: "{{ netdata_volume_name }}"
    size: "{{ netdata_volume_size }}"
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - netdata
    - filesystem

- name: Create the Netdata volume filesystem
  community.general.filesystem:
    device: "/dev/{{ netdata_volume_group }}/{{ netdata_volume_name }}"
    fstype: ext4
    opts: "{{ netdata_volume_options | default(omit) }}"
    state: present
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - netdata
    - filesystem

- name: Register and mount the Netdata volume
  ansible.posix.mount:
    src: "/dev/{{ netdata_volume_group }}/{{ netdata_volume_name }}"
    path: "{{ netdata_volume_path }}"
    fstype: ext4
    opts: defaults,rw,noatime,nosuid,noexec,nodev
    state: mounted
  tags:
    - netdata
    - filesystems
