---
# tasks file for secure_boot

# TODO: Check to see if the keys can be enrolled?

- name: Install the Secure Boot key manager locally
  community.general.pacman:
    name: "{{ secure_boot_packages }}"
    state: latest
  # Work on the assumption that the utility will have been pre-installed as part
  # of the bootstrap role when initialising the initial system, so only attempt
  # installation or update when bootstrap_mount_base is not set.
  when: |-
    not bootstrap_mount_base | default('') | length and
    device_type | default("virtual") == "physical"

- name: Ensure the Secure Boot keys are created in the chroot
  ansible.builtin.command: # noqa no-changed-when
    cmd: /usr/bin/arch-chroot {{ bootstrap_mount_base | default('') }} /usr/bin/fish -c 'sbctl create-keys'
  when: |-
    not ansible_check_mode and
    bootstrap_mount_base | default('') | length and
    device_type | default("virtual") == "physical"

- name: Ensure the Secure Boot keys are created locally
  ansible.builtin.command: # noqa no-changed-when
    cmd: sbctl create-keys
  when: |-
    not ansible_check_mode and
    not bootstrap_mount_base | default('') | length and
    device_type | default("virtual") == "physical"
