---
# tasks file for machines

- name: Create the logical volumes for the virtual machines
  community.general.lvol:
    vg: "{{ machine.1.vg | default('storage') }}"
    lv: "vm-{{ machine.0.environment }}-{{ machine.0.name }}-{{ machine.1.dev }}"
    size: "{{ machine.1.size }}"
  loop: "{{ machines_list | subelements('volumes', 'skip_missing=true') }}"
  loop_control:
    label: "/dev/{{ machine.1.vg | default('storage') }}/machine-{{ machine.0.environment }}-{{ machine.0.name }}-{{ machine.1.dev }}"
    loop_var: machine
  tags:
    - machines
    - logical

- name: Checking virtual machine definitions
  ansible.builtin.debug:
    msg: "{{ lookup('template', 'qemu.xml.jinja') }}"
    verbosity: 2
  loop: "{{ machines_list }}"
  loop_control:
    label: "{{ machine.name }}.{{ machine.environment[0:1] }}.{{ machine.location}}.kub3.uk"
    loop_var: machine

- name: Define the virtual machines
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'qemu.xml.jinja') }}"
  loop: "{{ machines_list }}"
  loop_control:
    label: "{{ machine.name }}.{{ machine.environment[0:1] }}.{{ machine.location}}.kub3.uk"
    loop_var: machine
  tags:
    - machines
    - configuration

- name: Start the virtual machines
  community.libvirt.virt:
    name: "vm-{{ machine.environment }}-{{ machine.name }}"
    command: start
    autostart: true
  loop: "{{ machines_list }}"
  loop_control:
    label: "{{ machine.name }}.{{ machine.environment[0:1] }}.{{ machine.location}}.kub3.uk"
    loop_var: machine
  tags:
    - machines
    - configuration
