---
# Node-specific configuration for node-06.p.cym-south-1.kub3.uk

filesystems_luks_enabled: true

systemd_networkd_ipv4_address: 172.23.32.2/24
systemd_networkd_ipv4_gateway: 172.23.32.1
systemd_networkd_ipv6_address: 2a02:8010:8006:3a32:4a21:bff:fe55:f393/64

systemd_networkd_vlans:
  - 32
  - 44
  - 45

machines_list:
  - name: boundary-03
    environment: production
    location: cym-south-1
    purpose: boundary-node
    vcpu: 2
    memory:
      current: 4
    volumes:
      - dev: vda
        size: 32G
    vlan: 44

  - name: consul-03
    environment: production
    location: cYm-south-1
    purpose: consul-node
    vcpu: 2
    memory:
      current: 2
    volumes:
      - dev: vda
        size: 32G
    vlan: 44

  - name: storage-03
    environment: development
    location: cym-south-1
    purpose: k8s-storage-node
    vcpu: 2
    memory:
      current: 8
    volumes:
      - dev: vda
        size: 64G
      - dev: vdb
        size: 1T
    vlan: 45

  - name: worker-06
    environment: production
    location: cym-south-1
    purpose: k8s-worker-node
    vcpu: 4
    memory:
      current: 12
    volumes:
      - dev: vda
        size: 128G
    vlan: 45
  - name: worker-12
    environment: production
    location: cym-south-1
    purpose: k8s-worker-node
    vcpu: 4
    memory:
      current: 12
    volumes:
      - dev: vda
        size: 128G
    vlan: 45
  - name: worker-18
    environment: production
    location: cym-south-1
    purpose: k8s-worker-node
    vcpu: 4
    memory:
      current: 12
    volumes:
      - dev: vda
        size: 128G
    vlan: 45
