---
env_purpose: k3s-single-node

systemd_networkd_ipv4_address: 172.23.39.3/24
systemd_networkd_ipv4_gateway: 172.23.39.1
systemd_networkd_ipv6_address: 2a02:8010:8006:3a39:1e:a3ff:fef7:def2/64

bird_interface: "br-*"

k3s_region: cym-south-1
k3s_zone: cym-south-1a

k3s_cluster_init: true

k3s_service_cidr: 172.24.4.0/22
k3s_cluster_dns: 172.24.4.10
k3s_cluster_cidr: 172.24.128.0/18
