---
# Node-specific configuration for vault-03.d.cym-south-1.kub3.uk

systemd_networkd_ipv4_address: 172.23.54.4/24
systemd_networkd_ipv4_gateway: 172.23.54.1
systemd_networkd_ipv6_address: 2a02:8010:8006:3a54:eb:7aff:fef5:b661/64
