---
# Node-specific configuration for vault-02.p.cym-south-1.kub3.uk

systemd_networkd_ipv4_address: 172.23.42.4/24
systemd_networkd_ipv4_gateway: 172.23.42.1
systemd_networkd_ipv6_address: 2a02:8010:8006:3a42:4c:39ff:fe4f:a52c/64
