---
# defaults file for bind

bind_listen_ipv4_addresses:
  - any
bind_listen_ipv6_addresses:
  - any
bind_port: 53

bind_dot_enable: true
bind_dot_port: 853

bind_doh_enable: true
bind_doh_port: 443

bind_dns64_hosts: []
bind_recursive_hosts: []

bind_forwarders: []
bind_forwarders_dot_enable: false
bind_forwarders_dot_name:
bind_forwarders_dot_port: 853
bind_forwarders_dot_ca_cert:

bind_views: []
# - name: example
#   comment: Comment goes here...
#   domains:
#     - name: example.com
#     - name: example.org
#       rfc2136: # master and slaves always has access via TSIG
#         - external-dns
#     - name: example.net
#       forwarders:
#         - 1.1.1.1
#   cidrs:
#     - comment: comment
#       address; 192.0.2.0/24
#     - address: 198.51.100.0/24
#     - address: 203.0.113.0/24
#     - address 2001:db8:1::/48
#     - address 2001:db8:2::/48
#     - address 2001:db8:3::/48
#   servers:
#     master: dns-01.example.com
#     slaves:
#       - name: dns-02.example.com
#         secret: ...
#       - name: dns-03.example.com
#         secret: ...
#   tsig:
#     master:
#       secret: ...
#     rfc2136:
#       - name: external-dns
#         grants:
#           - zonesub A AAAA CNAME TXT
#         cidrs:
#            - address: 10.0.0.0/8
#         secret: ...

bind_dnssec_validation: auto

bind_rndc_key_secret:
bind_rndc_group_members: []
# - user: jonathan
#   enabled: false
bind_tsig_group_members: []
# - user: jonathan
#   enabled: false
