---
# filesystem tasks for libvirtd

- name: Create the logical volume for virtual machine snapshots
  community.general.lvol:
    vg: "{{ libvirtd_snapshots_volume_group }}"
    lv: "{{ libvirtd_snapshots_volume_name }}"
    size: "{{ libvirtd_snapshots_volume_size }}"
  tags:
    - libvirtd
    - filesystems

- name: Create the snapshot volume filesystem
  community.general.filesystem:
    device: "/dev/{{ libvirtd_snapshots_volume_group }}/{{ libvirtd_snapshots_volume_name }}"
    fstype: ext4
    opts: "{{ libvirtd_snapshots_volume_options }}"
    state: present
  tags:
    - libvirtd
    - filesystems

- name: Register and mount the snapshot volume
  ansible.posix.mount:
    src: "/dev/{{ libvirtd_snapshots_volume_group }}/{{ libvirtd_snapshots_volume_name }}"
    path: /var/lib/libvirtd/qemu
    fstype: ext4
    opts: defaults,rw,noatime,nosuid,noexec,nodev
    state: mounted
  notify:
    - Restart libvirtd
  tags:
    - libvirtd
    - filesystems

- name: Set the directory permissions for snapshots
  ansible.builtin.file:
    path: /var/lib/libvirt/qemu
    owner: libvirt-qemu
    group: libvirt-qemu
    mode: u=rwx,g=rx,o=x
    state: directory
  notify:
    - Restart libvirtd
  tags:
    - libvirtd
    - filesystems
