---
# tasks file for libvirtd

- name: Check this role is not being run under bootstrap conditions
  ansible.builtin.fail:
    msg: This role does not support being run when bootstrapping hosts. Failing.
  when: bootstrap_mount_base | default('') | length

- name: Install the libvirt packages
  community.general.pacman:
    name: "{{ libvirtd_packages }}"
    state: latest
  ignore_errors: "{{ ansible_check_mode }}"
  tags:
    - libvirtd
    - packages

- name: Prepare the filesystem for libvirtd operations
  ansible.builtin.include_tasks: filesystem.yaml

- name: Prepare the services for libvirtd operations
  ansible.builtin.include_tasks: services.yaml

- name: Download installation images for libvirtd storage pool
  ansible.builtin.include_tasks: images.yaml

- name: Configure storage pools for libvirtd
  ansible.builtin.include_tasks: storage.yaml
