---
# handlers file for k3s

- name: Reload k3s
  ansible.builtin.systemd:
    name: k3s.service
    daemon_reload: false
    state: restarted

- name: Reload kernel modules
  # noqa no-changed-when
  ansible.builtin.command: |
    modprobe "{{ module }}"
  loop: "{{ k3s_kernel_modules }}"
  loop_control:
    label: "{{ module }}"
    loop_var: module

- name: Reload sysctl settings
  # noqa no-changed-when
  ansible.builtin.command: |
    sysctl --system
