---
# tasks file for k3s

- name: Check this role is not being run under bootstrap conditions
  ansible.builtin.fail:
    msg: This role does not support being run when bootstrapping hosts. Failing.
  when: bootstrap_mount_base | default('') | length

- name: Configure required kernel modules
  ansible.builtin.template:
    src: modules.conf.jinja
    dest: /etc/modules-load.d/80-k3s.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - Reload kernel modules
  tags:
    - k3s
    - modules
    - configuraton

- name: Configure sysctl settings
  ansible.builtin.template:
    src: sysctl.conf.jinja
    dest: /etc/sysctl.d/80-k3s.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - Reload sysctl settings
  tags:
    - k3s
    - sysctl
    - configuraton

- name: Install k3s pre-requisites
  community.general.pacman:
    name: "{{ k3s_packages }}"
    state: latest
    force: true
    extra_args: --noconfirm
  tags:
    - k3s
    - package

- name: Ensure required k3s services are enabled
  ansible.builtin.systemd_service:
    name: "{{ service }}"
    enabled: true
    state: started
  loop: "{{ k3s_services }}"
  loop_control:
    label: "{{ service }}"
    loop_var: service
  tags:
    - k3s
    - service

- name: Prepare the k3s directories
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - /etc/rancher/k3s/config.yaml.d
    - /etc/systemd/system/k3s.service.d
  loop_control:
    loop_var: directory
    label: "{{ directory }}"
  tags:
    - k3s
    - configuration

- name: Install the k3s.service overrides
  ansible.builtin.template:
    src: "{{ override }}.jinja"
    dest: "/etc/systemd/system/k3s.service.d/{{ override }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  loop:
    - service.conf
    - unit.conf
  loop_control:
    loop_var: override
    label: "/etc/systemd/system/k3s.service.d/{{ override }}"
  notify:
    - Reload k3s
  tags:
    - k3s
    - service

- name: Install the general k3s configuration
  ansible.builtin.template:
    src: config.yaml.jinja
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - Reload k3s
  tags:
    - k3s
    - configuraton

- name: Install the drop-in k3s configurations
  ansible.builtin.template:
    src: "{{ config }}.jinja"
    dest: "/etc/rancher/k3s/config.yaml.d/{{ config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: k3s_node_type == "server" or config != "server.yaml"
  loop:
    - server.yaml
    - agent.yaml
    - cluster.yaml
    - node.yaml
  loop_control:
    loop_var: config
    label: "/etc/rancher/k3s/config.yaml.d/{{ config }}"
  notify:
    - Reload k3s
  tags:
    - k3s
    - configuraton
