---
# root tasks for users

- name: Configure the root user
  ansible.builtin.user:
    name: root
    shell: "{{ users_root.shell | default(users_default_shell) }}"
  tags:
    - users
    - root
    - configuration

# The root user is always configured on bootstrapping, so just ensure the
# credentials (i.e. password and SSH public keys) are up-to-date

- name: Set the root user password
  ansible.builtin.user:
    name: root
    password: "{{ users_root_password }}"
    update_password: always
  when: users_root_password is defined
  tags:
    - users
    - root
    - password

- name: Clear the root user authorized_keys
  # The root user is disabled in SSH, so it cannot be accessed remotely and as
  # such all SSH keys should be deleted to act as a further backup
  ansible.builtin.file:
    dest: /root/.ssh/authorized_keys
    state: absent
  tags:
    - users
    - root
    - authorized_keys
