---
# user tasks for users

- name: Configure the group {{ user }}
  ansible.builtin.group:
    name: "{{ user }}"
  tags:
    - groups
    - configuration

- name: Configure the user {{ user }}
  ansible.builtin.user:
    name: "{{ user }}"
    shell: "{{ settings.shell | default(users_default_shell) }}"
    groups: "{{ [user] + (settings.groups | default(users_default_groups)) }}"
    append: false
  tags:
    - users
    - configuration

# The root user is always configured on bootstrapping, so just ensure the
# credentials (i.e. password and SSH public keys) are up-to-date

- name: Set the password for {{ user }}
  ansible.builtin.user:
    name: root
    password: "{{ settings.password }}"
    update_password: always
  when: settings.password is defined
  tags:
    - users
    - password

- name: Clear the root user authorized_keys
  # The root user is disabled in SSH, so it cannot be accessed remotely and as
  # such all SSH keys should be deleted to act as a further backup
  ansible.posix.file:
    path: /root/.ssh/authorized_keys
    state: absent
  tags:
    - users
    - root
    - authorized_keys
