---
# create physical tasks file for filesystems

- name: Create LUKS container on physical partitions
  community.crypto.luks_device:
    # yamllint disable-line rule:line-length
    device: /dev/{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ item.number }}
    type: luks2
    cipher: aes-xts-plain64
    keysize: 512
    hash: sha256
    passphrase: "{{ filesystems_crypt_passphrase }}"
    state: present
  loop: "{{ filesystems_physical_partitions | default([]) }}"
  loop_control:
    # yamllint disable-line rule:line-length
    label: /dev/{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ item.number }}
  when: item.luks|default(false)
  tags:
    - filesystems
    - setup
    - physical
    - cryptsetup

- name: Open LUKS containers on physical partitions
  community.crypto.luks_device:
    # yamllint disable-line rule:line-length
    device: /dev/{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ item.number }}
    # yamllint disable-line rule:line-length
    name: crypt-{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ item.number }}
    state: opened
    passphrase: "{{ filesystems_crypt_passphrase }}"
  loop: "{{ filesystems_physical_partitions | default([]) }}"
  loop_control:
    # yamllint disable-line rule:line-length
    label: /dev/{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ item.number }}
  when: item.luks|default(false)
  tags:
    - filesystems
    - setup
    - physical

- name: Create the physical volume filesystems
  community.general.filesystem:
    # yamllint disable-line rule:line-length
    device: /dev/{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ ansible_loop.index }}
    fstype: "{{ item.fs_type }}"
    opts: "{{ item.fs_opts | default(omit) }}"
    state: present
    force: true
  when: item.fs_type is defined
  ignore_errors: "{{ ansible_check_mode }}"
  loop: "{{ filesystems_physical_partitions | default([]) }}"
  loop_control:
    # yamllint disable-line rule:line-length
    label: /dev/{{ item.device }}{% if item.device[:4] == 'nvme' %}p{% endif %}{{ item.number }}
    extended: true
  tags:
    - filesystems
    - setup
    - physical
