---
# wipe tasks file for filesystems

- name: "Unmount all filesystems from {{ filesystems_mount_base }}"
  # This has to be run as a shell command as ansible.posix.mount does not
  # support recursive unmounts and we need to ensure the base mount is clear
  ansible.builtin.shell: # noqa no-changed-when
    cmd: |-
      umount -R {{ filesystems_mount_base }} 2>/dev/null \
        || true
    executable: /usr/bin/bash
  when: not ansible_check_mode
  tags:
    - filesystems
    - mount
    - wipe
    - logical
    - physical

- name: Clean up logical volumes and groups
  ansible.builtin.import_tasks: wipe-logical.yaml

- name: Clean up physical partitions
  ansible.builtin.include_tasks: wipe-physical.yaml
  loop: "{{ filesystems_physical_drives }}"
  loop_control:
    label: "/dev/{{ drive }}"
    loop_var: drive
