---
- name: Gather Facts from ACME Hosts
  hosts: ca
  # This play is purely to gather the facts from the ACME hosts for use in
  # helping generate the necessary firewall rules for HTTP-01 validation in the
  # following play
  gather_facts: true

- name: Configure Authentik Hosts
  hosts: authentik
  become: true
  become_user: root
  roles:
    - role: ufw
      tags:
        - ufw
    - role: caddy
      tags:
        - caddy
    - role: lego
      tags:
        - lego
    - role: postgresql
      tags:
        - postgresql
    - role: authentik
      tags:
        - authentik
    - role: tailscale
      tags:
        - tailscale
    - role: cloudflared
      tags:
        - cloudflare
