---
- name: Configure Authentik nodes
  hosts: authentik
  become: true
  become_user: root

  # Each Authentik node must know about the configuration of the CA nodes, in
  # order to permit the necessary firewall rules for HTTP-01 validation
  pre_tasks:
    - name: Gather facts from all Certificate Authority hosts
      ansible.builtin.setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item].ansible.default_ipv4 is not defined
      with_items: "{{ groups['ca'] }}"

  roles:
    - role: ufw
      tags:
        - ufw
    - role: caddy
      tags:
        - caddy
    - role: lego
      tags:
        - lego
    - role: postgresql
      tags:
        - postgresql
    - role: authentik
      tags:
        - authentik
    - role: tailscale
      tags:
        - tailscale
    - role: cloudflared
      tags:
        - cloudflare
