---
- name: Baseline all hosts
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ca
    - role: pacman
    - role: issue
    - role: kernels
    - role: systemd
    - role: systemd_networkd
    - role: systemd_resolved
    - role: ca
    - role: firewalld
    - role: ssh
    - role: starship
    - role: fish
    - role: bash
    - role: sudo
    - role: users
    - role: logrotate
  tags:
    - update
