---
- name: Update all Arch Linux hosts
  hosts: arch
  become: true
  become_user: root
  roles:
    # - role: ca
    - role: pacman
  tags:
    - update

- name: Update all Debian Linux hosts
  hosts: debian
  become: true
  become_user: root
  roles: []
  # - role: ca
  # - role: apt
  tags:
    - update

- name: Baseline all Arch Linux Hosts
  hosts: arch
  become: true
  become_user: root
  roles:
    - role: kernels
    - role: systemd
    - role: systemd_networkd
    - role: systemd_resolved
    - role: ufw
  tags:
    - baseline

- name: Baseline all hosts
  hosts: all
  become: true
  become_user: root
  roles:
    - role: starship
    - role: fish
    - role: bash
    - role: sudo
    - role: users
    - role: issue
    - role: ssh
  tags:
    - baseline
