---
- name: Update all Arch Linux hosts
  hosts: arch
  become: true
  become_user: root
  roles:
    # - role: ca
    #   tags:
    #     - ca
    - role: pacman
      tags:
        - pacman
  tags:
    - update

- name: Update all Debian Linux hosts
  hosts: debian
  become: true
  become_user: root
  roles: []
    # - role: ca
    #   tags:
    #     - ca
    # - role: apt
    #   tags:
    #     - ca
  tags:
    - update

- name: Baseline all Arch Linux Hosts
  hosts: arch
  become: true
  become_user: root
  roles:
    - role: kernels
      tags:
        - kernels
    - role: systemd
      tags:
        - systemd
    - role: systemd_networkd
      tags:
        - systemd_networkd
    - role: systemd_resolved
      tags:
        - systemd_resolved
    - role: ufw
      tags:
        - ufw
  tags:
    - baseline

- name: Baseline all hosts
  hosts: all
  become: true
  become_user: root
  roles:
    # - role: ca
    #   tags:
    #     - ca
    - role: starship
      tags:
        - starship
    - role: fish
      tags:
        - tailscale
    - role: bash
      tags:
        - bash
    - role: sudo
      tags:
        - sudo
    - role: users
      tags:
        - users
    - role: issue
      tags:
        - issue
    - role: ssh
      tags:
        - ssh
  tags:
    - baseline
