---
- name: Configure Bind Services
  hosts: bind
  become: true
  become_user: root

  # Each BIND node must know about the configuration of the other BIND nodes in
  # order to correctly configure the BIND server for replication and permit the
  # necessary traffic via the firewall rules
  pre_tasks:
    - name: Gather facts from all BIND hosts
      ansible.builtin.setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item].ansible.ansible_hostname is not defined
      with_items: "{{ groups['bind'] }}"

  roles:
    - role: bind
      tags:
        - bind
