---
# Configure the caching service for Arch Linux repositories

- name: Configure the caching service for Arch Linux repositories
  hosts: cache
  become: true
  become_user: root
  roles:
    - role: nginx
    - role: cache
