---
- name: Configure DNS Hosts
  hosts: dns
  become: true
  become_user: root

  roles:
    - role: ufw
      tags:
        - ufw
    - role: tailscale
      tags:
        - tailscale

# Include a dedicated play for installing and managing the BIND service, as it
# needs to some steps to configure the BIND service and firewall rules that are
# specific to the BIND service
- name: Configure Bind Services
  import_playbook: bind.yaml
  when: "'bind' in group_names"
  tags:
    - bind
