---
- name: Set up and launch all virtual machines physical nodes
  hosts: nodes
  become: true
  become_user: root
  roles:
    # - role: systemd_networkd
    - role: libvirtd
  tags:
    - virtual-machines
