---
- name: Set up and launch all virtual machines on physical nodes
  hosts: nodes
  become: true
  become_user: root
  roles:
    - role: systemd_networkd
    - role: libvirtd
    - role: machines
  tags:
    - libvirtd
    - machines
