---
# Configure the caching service for Arch Linux repositories

- name: Configure the highly-avilable load balancers for internal requests
  hosts: haproxy
  become: true
  become_user: root
  roles:
    - role: systemd_networkd
    - role: bird
