---
# Configure the caching service for Arch Linux repositories

- name: Configure the host for a single-node Kubernetes deployment
  hosts: minikube
  become: true
  become_user: root
  roles:
    # - role: bird
    - role: k3s
