---
# Upgrade all the installed packages on all virtual, and the physical hosts,
# updating the virtual hosts first and completely before updating the physical
# hosts.

- name: Update all machines
  ansible.builtin.import_playbook: update.yaml

- name: Upgrade all physical machines
  hosts: physical
  become: true
  become_user: root
  tasks:
    - name: Upgrade the keyrings first
      community.general.pacman:
        name:
          - archlinux-keyring
          - alhp-keyring
        state: latest
      tags:
        - pacman
    - name: Upgrade all available packages
      community.general.pacman:
        upgrade: true
      tags:
        - pacman
  tags:
    - physical-machines

- name: Upgrade all virtual machines
  hosts: virtual
  become: true
  become_user: root
  tasks:
    - name: Upgrade the keyrings first
      community.general.pacman:
        name:
          - archlinux-keyring
          - alhp-keyring
        state: latest
      tags:
        - pacman
    - name: Upgrade all available packages
      community.general.pacman:
        upgrade: true
      tags:
        - pacman
  tags:
    - virtual-machines

- name: Upgrade all Caddy servers
  # This will target both Proxmox hosts and Authentik servers
  hosts: proxmox:authentik
  become: true
  become_user: root
  vars:
    caddy_upgrade: true
  roles:
    - role: caddy
      tags:
        - caddy
  tags:
    - caddy
