---
# Upgrade all the installed packages on all virtual, and the physical hosts,
# updating the virtual hosts first and completely before updating the physical
# hosts.

- name: Update all machines
  ansible.builtin.import_playbook: update.yaml

- name: Upgrade all virtual machines
  hosts: virtual:!remote
  become: true
  become_user: root
  tasks:
    - name: Upgrade the keyrings first
      community.general.pacman:
        name:
          - archlinux-keyring
          - alhp-keyring
        state: latest
    - name: Upgrade all available packages
      community.general.pacman:
        upgrade: true
  tags:
    - virtual-machines

- name: Upgrade all physical machines
  hosts: physical
  become: true
  become_user: root
  tasks:
    - name: Upgrade the keyrings first
      community.general.pacman:
        name:
          - archlinux-keyring
          - alhp-keyring
        state: latest
    - name: Upgrade all available packages
      community.general.pacman:
        upgrade: true
  tags:
    - physical-machines
