---
# vars file for k3s

k3s_packages:
  - conntrack-tools
  - k3s-1.29-bin
  - cni-plugins
  - containerd
  - nerdctl
  - kubectl

k3s_services:
  - conntrackd.service
  - containerd.service

k3s_kernel_modules:
  - overlay
  - br_netfilter

k3s_sysctl_settings:
  - key: net.bridge.bridge-nf-call-iptables
    value: 1
  - key: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - key: net.ipv4.ip_forward
    value: 1
