---
env_purpose: external-node

filesystems_physical_drives:
  - vda

filesystems_physical_partitions:
  - name: GRUB
    device: vda
    number: 1
    start: 1MiB
    end: 3MiB
    flags:
      - bios_grub
  - name: ESP
    device: vda
    number: 2
    path: /efi
    start: 3MiB
    end: 256MiB
    flags:
      - esp
    pv_type: fat32
    fs_type: vfat
    fs_opts: -F 32 -n ESP
  - name: LVM
    device: vda
    number: 3
    start: 256MiB
    end: 100%
    flags:
      - lvm

filesystems_volume_groups:
  - name: storage
    partitions:
      - /dev/vda3

filesystems_logical_volumes:
  - name: system
    group: storage
    path: /
    size: 8G
    fs_type: ext4
    fs_opts: -L SYSTEM
  - name: swap
    group: storage
    size: 1G
    fs_type: swap
    fs_opts: -L SWAP
  - name: journald
    group: storage
    path: /var/log/journal
    size: 256M
    fs_type: ext4
    fs_opts: -L JOURNALD
    mount_opts:
      - nosuid
  - name: pacman
    group: storage
    path: /var/cache/pacman
    size: 2G
    fs_type: ext4
    fs_opts: -L PACMAN
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: home
    group: storage
    path: /home
    size: 256M
    fs_type: ext4
    fs_opts: -L HOME
    mount_opts:
      - nosuid
      - nodev
  - name: named
    group: storage
    path: /var/lib/named
    size: 1G
    fs_type: ext4
    fs_opts: -L NAMED
    mount_opts:
      - nosuid
  - name: openbao
    group: storage
    path: /var/lib/openbao
    size: 4G
    fs_type: ext4
    fs_opts: -L OPENBAO
    mount_opts:
      - nosuid

# These nodes are not QEMU hosts, so remove the QEMU packages from the pacstrap
# installation step, but we do require GRUB instead, so add that to the list
bootstrap_pacstrap_extras:
  - grub

# These are nodes running via Mythic Beasts on KVM hypervisors with only BIOS
# boot support, so must use GRUB as the bootloader
kernels_bootloader: grub

# This node is outside the Bridgend network, therefore the default firewall
# rules which include internal IPv4 addresses is not appropriate. Add a custom
# set of rules which to allow SSH from anywhere (these are dedicated remote
# access hosts).
ufw_default_rules:
  - rule: allow
    proto: tcp
    port: 22
    comment: Allow SSH from anywhere

lego_acme_email: admin@n3t.uk
lego_acme_server: https://ca.n3t.uk/acme/n3tuk/directory
lego_acme_servers_group: ca
lego_acme_mode: standalone

tailscale_exit_node: true
tailscale_peer_relay: true
tailscale_auth_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  39353861626532386266626139663164313461336330663538393136353233663133376534373637
  3931313263333632663631316561333534663362383234650a393262363431653137643139373337
  63656232376635356464643832613361333462313130373561343532353338363230646363623335
  3663346134366462620a326333306464313861326562353964303630643639656239643137366234
  38313662353631653030663964383262666139326162353738653137333465633032313738653437
  62376435333933343266343035356563316562643138383963313662663533393633656333663039
  343561386239333536316634663434636464

bind_recursive_hosts:
  - comment: >-
      n3tuk IPv6 network
    address: 2a02:8010:8006::/48
  - comment: >-
      n3t.uk Tailscale Network
    address: fd7a:115c:a1e0::/64
  - address: 100.64.0.0/10
  - comment: >-
      external-01.london.n3t.uk Server
    address: 2a00:1098:5bf::1/128
  - comment: >-
      external-02.amsterdam.n3t.uk Server
    address: 2a00:1098:5bf::2/128

lego_firewall_ipv4_replace:
  "172.23.41.4": "82.69.106.64"
  # We'll skip this address as the above address will effectively install the
  # external IP address for both of the CA servers by the one rule
  "172.23.41.5": skipped
