---
# Kubernetes nodes cannot operate with swap enabled, so ensure the filesystems
# are reconfigured to exclude that list.
filesystems_logical_volumes:
  - name: system
    group: storage
    path: /
    size: 8G
    fs_type: ext4
    fs_opts: -L SYSTEM
  - name: journald
    group: storage
    path: /var/log/journal
    size: 256M
    fs_type: ext4
    fs_opts: -L JOURNALD
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: pacman
    group: storage
    path: /var/cache/pacman
    size: 2G
    fs_type: ext4
    fs_opts: -L PACMAN
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: home
    group: storage
    path: /home
    size: 256M
    fs_type: ext4
    fs_opts: -L HOME
    mount_opts:
      - nosuid
      - nodev
  - name: rancher
    group: storage
    path: /var/lib/rancher
    size: 32G
    fs_type: ext4
    fs_opts: -L RANCHER
