---
device_type: physical

filesystems_physical_drives:
  - /dev/nvme0n1

filesystems_physical_partitions:
  - name: ESP
    device: nvme0n1
    number: 1
    path: /efi
    start: 1MiB
    end: 512MiB
    flags:
      - boot
    pv_type: fat32
    fs_type: vfat
    fs_opts: -F 32 -n ESP
  - name: LVM
    device: nvme0n1
    number: 2
    start: 512MiB
    end: 100%
    flags:
      - lvm
    luks: true

filesystems_volume_groups:
  - name: storage
    partitions:
      - /dev/mapper/crypt-nvme0n1p2

filesystems_logical_volumes:
  - name: system
    group: storage
    path: /
    size: 8G
    fs_type: ext4
    fs_opts: -L SYSTEM
  - name: pacman
    group: storage
    path: /var/cache/pacman
    size: 4G
    fs_type: ext4
    fs_opts: -L PACMAN
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: swap
    group: storage
    size: 16G
    fs_type: swap
    fs_opts: -L SWAP
  - name: journald
    group: storage
    path: /var/log/journal
    size: 256M
    fs_type: ext4
    fs_opts: -L JOURNALD
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: images
    group: storage
    path: /var/lib/libvirt/images
    size: 4G
    fs_type: ext4
    fs_opts: -L IMAGES
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: home
    group: storage
    path: /home
    size: 256M
    fs_type: ext4
    fs_opts: -L HOME
    mount_opts:
      - nosuid
      - nodev

filesystems_tmpfs_size: 1G

# Additional packages which are specifically related to this node being a
# physical node (e.g. it requires ucode and the TPM2 tools)
bootstrap_pacstrap_extras:
  - intel-ucode
  - tpm2-tools
  - sbctl
  - sbsigntools
  - i7z
  - libvirt
  - dmidecode
  - qemu-desktop
  - jack2

kernels_microcode: true
kernels_secure_boot_sign: true
kernels_install:
  - linux-hardened
  - linux-lts

kernels_mkinitcpio_modules:
  - i915
  - intel_lpss_pci
kernels_mkinitcpio_hooks:
  - base
  - systemd
  - keyboard
  - autodetect
  - modconf
  - kms
  - block
  - sd-vconsole
  - sd-encrypt
  - lvm2
  - filesystems
  - fsck

systemd_system_watchdog_enabled: true
systemd_journald_max_size: 200M
systemd_timesyncd_fallback_ntp:
  - ntp0.zen.co.uk
  - ntp1.zen.co.uk

# Add the libvirt group to the following users to allow access to the libvirt
# daemon on the physical hosts, allowing these users to manage virtual machines
users_users:
  jonathan:
    groups:
      - power
      - wheel
      - users
      - libvirt
