---
filesystem_physical_drives:
  - /dev/nvme0n1

filesystem_physical_partitions:
  - name: ESP
    device: nvme0n1
    number: 1
    path: /efi
    start: 1MiB
    end: 512MiB
    flags:
      - boot
    pv_type: fat32
    fs_type: vfat
    fs_opts: -F 32 -n ESP
  - name: LVM
    device: nvme0n1
    number: 2
    start: 512MiB
    end: 100%
    flags:
      - lvm

filesystem_volume_groups:
  - name: storage
    partitions:
      - /dev/nvme0n1p2

filesystem_logical_volumes:
  - name: system
    group: storage
    path: /
    size: 8G
    fs_type: ext4
    fs_opts: -L SYSTEM
  - name: swap
    group: storage
    size: 8G
    fs_type: swap
    fs_opts: -L SWAP
  - name: pacman
    group: storage
    path: /var/lib/pacman
    size: 2G
    fs_type: ext4
    fs_opts: -L PACMAN
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: journald
    group: storage
    path: /var/log/journal
    size: 1G
    fs_type: ext4
    fs_opts: -L JOURNALD
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: images
    group: storage
    path: /var/lib/libvirt/images
    size: 4G
    fs_type: ext4
    fs_opts: -L IMAGES
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: home
    group: storage
    path: /mnt/home
    size: 256M
    fs_type: ext4
    fs_opts: -L HOME
    mount_opts:
      - nosuid
      - nodev

filesystem_tmpfs_size: 1G

bootstrap_pacstrap_extras:
  - linux-firmware
  - intel-ucode

bootstrap_timedatectl: true
