---
device_type: virtual

filesystems_physical_drives:
  - vda

filesystems_physical_partitions:
  - name: ESP
    device: vda
    number: 1
    path: /efi
    start: 1MiB
    end: 256MiB
    flags:
      - esp
    pv_type: fat32
    fs_type: vfat
    fs_opts: -F 32 -n ESP
  - name: LVM
    device: vda
    number: 2
    start: 256MiB
    end: 100%
    flags:
      - lvm

filesystems_volume_groups:
  - name: storage
    partitions:
      - /dev/vda2

filesystems_logical_volumes:
  - name: system
    group: storage
    path: /
    size: 8G
    fs_type: ext4
    fs_opts: -L SYSTEM
  - name: swap
    group: storage
    size: 1G
    fs_type: swap
    fs_opts: -L SWAP
  - name: journald
    group: storage
    path: /var/log/journal
    size: 256M
    fs_type: ext4
    fs_opts: -L JOURNALD
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: pacman
    group: storage
    path: /var/cache/pacman
    size: 2G
    fs_type: ext4
    fs_opts: -L PACMAN
    mount_opts:
      - nosuid
      - nodev
      - noexec
  - name: home
    group: storage
    path: /mnt/home
    size: 256M
    fs_type: ext4
    fs_opts: -L HOME
    mount_opts:
      - nosuid
      - nodev

kernels_microcode: false
kernels_kernels:
  - linux-hardened
  - linux-lts

kernels_mkinitcpio_modules:
  - virtio-gpu

systemd_journald_max_size: 200M

firewalld_public_interface: "{{ systemd_networkd_ethernet_name }}"
