---
# tasks file for firewalld

- name: Check this role is not being run under bootstrap conditions
  ansible.builtin.fail:
    msg: This role does not support being run when bootstrapping hosts. Failing.
  when: bootstrap_mount_base | default('') | length

- name: Install firewalld
  community.general.pacman:
    name: "{{ firewalld_packages }}"
    state: latest
  tags:
    - firewalld
    - package

- name: Ensure firewalld is enabled
  ansible.builtin.systemd_service:
    name: firewalld.service
    enabled: true
    state: started
  tags:
    - firewalld
    - service

- name: Configure the Services for firewalld
  ansible.builtin.include_tasks: services.yaml

- name: Configure the Zones for firewalld
  ansible.builtin.include_tasks: zones.yaml

- name: Configure the Interfaces for firewalld
  ansible.builtin.include_tasks: interfaces.yaml
