---
# handlers file for kernels

- name: Run mkinitcpio locally
  # This handler is building the kernel initramfs and EFI stub kernel files
  # specifically inside non-chroot'd environments
  ansible.builtin.command: # noqa no-changed-when
    cmd: mkinitcpio -P
  when: bootstrap_mount_base | default('') | length == 0

- name: Run sbctl sign-all locally
  # This handler is signing kernels specifically inside non-chroot'd
  # environments and on physical machines only
  ansible.builtin.command: # noqa no-changed-when
    cmd: sbctl sign-all
  when: >-
    bootstrap_mount_base | default('') | length == 0 and
    device_type | default("virtual") == "physical"

- name: Run grub-install locally
  ansible.builtin.command: # noqa no-changed-when
    argv:
      - grub-install
      - --target=i386-pc
      - /dev/{{ filesystems_physical_drives | first }}
  when: >-
    bootstrap_mount_base | default('') | length == 0 and
    device_type | default("virtual") == "virtual" and
    kernels_bootloader == "grub"

- name: Run grub-mkconfig locally
  ansible.builtin.command: # noqa no-changed-when
    cmd: grub-mkconfig -o /boot/grub/grub.cfg
  when: >-
    bootstrap_mount_base | default('') | length == 0 and
    device_type | default("virtual") == "virtual" and
    kernels_bootloader == "grub"
