---
# handlers file for kernels

- name: Run mkinitcpio locally
  # This handler is building the kernel initramfs and EFI stub kernel files
  # specifically inside non-chroot'd environments
  ansible.builtin.command: # noqa no-changed-when
    cmd: mkinitcpio -P
  when: not bootstrap_mount_base | default('') | length

- name: Run sbctl sign-all locally
  # This handler is signing kernels specifically inside non-chroot'd
  # environments and on physical machines only
  ansible.builtin.command: # noqa no-changed-when
    cmd: sbctl sign-all
  when: |-
    not bootstrap_mount_base | default('') | length and
    device_type | default("virtual") == "physical"
