---
# defaults file for k3s

k3s_node_type: server

k3s_node_region: unknown-1
k3s_node_zone: unknown-1a

k3s_node_labels: []
k3s_node_taints: []

k3s_node_name: "{{ ansible_hostname }}"
k3s_bind_address: "{{ ansible_default_ipv4.address }}"
k3s_https_listen_port: 6433

k3s_flannel_backend: vxlan
k3s_service_cidr: 172.23.8.0/21
k3s_cluster_dns: 172.23.8.10
k3s_cluster_cidr: 172.23.16.0/20
k3s_egress_selector_mode: agent

k3s_cluster_init: false
k3s_tls_san:
  - "{{ ansible_fqdn }}"

k3s_disable_helm_controller: true
k3s_disable_network_policy: true
k3s_disable_embedded_registry: true

k3s_service_disable:
  - servicelb
  - traefik
  - local-storage
  - metrics-server
