---
# service-specific tasks file for bind

- name: Start and enable the BIND service
  ansible.builtin.systemd:
    name: "{{ bind_service_name }}.service"
    enabled: true
    state: started
  when: >-
    not ansible_check_mode
  tags:
    - bind
    - systemd
    - service

- name: Enable the Lego certificate renewal timer
  ansible.builtin.systemd:
    name: "lego@{{ bind_service_name }}.timer"
    enabled: true
    state: started
  when: >-
    ( bind_doh_enable or bind_dot_enable ) and
    not ansible_check_mode
  tags:
    - bind
    - systemd
    - service
