---
# virtual machine kernel tasks for kernels

- name: Configure systemd-boot entry for {{ kernel }}
  ansible.builtin.template:
    src: entry.conf.jinja
    # yamllint disable-line rule:line-length
    dest: "{{ bootstrap_mount_base | default('') }}/efi/loader/entries/{{ kernel }}.conf"
    owner: root
    group: root
    # This file is installed on a FAT32 filesystem, so the executable bit is
    # required to prevent "configuration drift" from constantly trying to reset
    # the file permissions.
    mode: u=rwx,g=rx,o=rx
  when: kernels_bootloader == "bootctl"
  tags:
    - kernel
    - systemd-boot
    - configuration

- name: Force running grub-mkconfig in the chroot for {{ kernel }}
  # This handler is building files specifically inside chroot'd environments
  ansible.builtin.command: # noqa no-changed-when
    cmd: >-
      /usr/bin/arch-chroot {{ bootstrap_mount_base | default('') }}
        /usr/bin/fish -c 'grub-mkconfig -o /boot/grub/grub.cfg'
  # If the kernel has been installed via pacstrap, rather than pacman above,
  # then the installation of the presets will be after installation, so force
  # the run when bootstrap_mount_base is configured to handle this
  when: >-
    bootstrap_mount_base | default('') | length > 0 and
    kernels_bootloader == "grub"
  tags:
    - kernel
    - grub
    - configuration
