---
# virtual machine kernel tasks for kernels

- name: Configure systemd-boot entry for {{ kernel }}
  ansible.builtin.template:
    src: entry.conf.jinja
    dest: "{{ bootstrap_mount_base | default('') }}/efi/loader/entries/{{ kernel }}.conf"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  tags:
    - kernel
    - systemd-boot
    - configuration
